trigger:
  branches:
    include:
      - main
  paths:
    include:
      - cfn/*
      - .azure/pipelines/*

variables:
  - group: cfn-practice-secrets
  - name: STACK_NAME
    value: cfn-practice-azdo
  - name: TEMPLATE_FILE
    value: cfn/template.yaml

pool:
  vmImage: ubuntu-latest

steps:
  - checkout: self

  - script: pip install cfn-lint --quiet
    displayName: Install cfn-lint

  - script: bash scripts/pipeline/deploy.sh
    displayName: Deploy CloudFormation Stack
    env:
      STACK_NAME: $(STACK_NAME)
      TEMPLATE_FILE: $(TEMPLATE_FILE)
      AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
      AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)
      AWS_REGION: $(AWS_REGION)
